version: '3'

services:
  # development database
  postgres:
    container_name: telephony-pg
    image: bitnami/postgresql:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telephony-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    container_name: telephony-api 
    image: telephony
    depends_on:
      postgres:
        condition: service_healthy 
    build: 
      context: .
      dockerfile: Dockerfile
    # depends on the api port
    ports: 
      - "3000:3000"
    env_file:
      - .env