@baseUrl = http://localhost:3001/api/v1
@accessToken = {{login.response.body.data.access_token}}


# @name ping
GET {{baseUrl}}/welcome
Content-Type: application/json

###

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "first_name": "dummy example",
    "last_name": "dummy example",
    "email": "change@dummy.com",
    "password": "password123"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "change@dummy.com",
    "password": "password123"
}

###

# @name me
GET {{baseUrl}}/me
Authorization: Bearer {{accessToken}}

###

# @name create_profile
POST {{baseUrl}}/me/profile
Authorization: Bearer {{accessToken}}

{
  "bio": "short bio",
  "display_name": "dummy user 2",
  "user_id": 2
}

###

# @name create_guild
POST {{baseUrl}}/guilds
Authorization: Bearer {{accessToken}}

{
  "name": "dummy guild",
  "description": "dummy descrption",
  "profile_id": 1
}

###

# @name fetch_guilds
GET {{baseUrl}}/guilds
Authorization: Bearer {{accessToken}}

###

# @name fetch_guild_channels
GET {{baseUrl}}/guilds/1/channels
Authorization: Bearer {{accessToken}}

{
  "profile_id": 2
}

###

# @name create_channel
POST {{baseUrl}}/ws/guilds/1/channels
Authorization: Bearer {{accessToken}}

{
  "name": "dummy ch",
  "profile_id": 1
}

###

# @name join_guild
POST {{baseUrl}}/guilds/1/join
Authorization: Bearer {{accessToken}}

{
  "profile_id": 2
}

###

# @name join_channel
POST {{baseUrl}}/ws/guilds/3/channels/:channel_id/join
Authorization: Bearer {{accessToken}}

{
  "profile_id": 1
}