@baseUrl = http://localhost:3001/api/v1

# @name ping
GET {{baseUrl}}/welcome
Content-Type: application/json

###

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "first_name": "dummy example",
    "last_name": "dummy example",
    "email": "dummy@email.com",
    "password": "password123"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "dummy@email.com",
    "password": "password123"
}