basePath: /api/v1
definitions:
  endpoint.CreateChannelRequest:
    properties:
      name:
        type: string
      profile_id:
        type: integer
    required:
    - name
    - profile_id
    type: object
  endpoint.CreateGuildRequest:
    properties:
      description:
        type: string
      name:
        type: string
      profile_id:
        type: integer
    required:
    - description
    - name
    - profile_id
    type: object
  endpoint.CreateProfileRequest:
    properties:
      bio:
        type: string
      display_name:
        type: string
    required:
    - bio
    - display_name
    type: object
  endpoint.CredentialsAuthData:
    properties:
      access_token:
        type: string
    type: object
  endpoint.CredentialsAuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  endpoint.CredentialsAuthResponse:
    properties:
      data:
        $ref: '#/definitions/endpoint.CredentialsAuthData'
      message:
        type: string
      status_code:
        type: integer
    type: object
  endpoint.FetchAvailableGuildsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/entity.Guild'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  endpoint.FetchGuildChannelsRequest:
    properties:
      profile_id:
        type: integer
    type: object
  endpoint.FetchGuildChannelsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/entity.Channel'
        type: array
      message:
        type: string
      status_code:
        type: integer
    type: object
  endpoint.MeResponse:
    properties:
      data:
        $ref: '#/definitions/entity.UserProfile'
      message:
        type: string
      status_code:
        type: integer
    type: object
  endpoint.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  endpoint.Response:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
  entity.Channel:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      guild_id:
        type: integer
      id:
        type: integer
      messages_quantity:
        type: integer
      name:
        maxLength: 36
        minLength: 1
        type: string
      owner_id:
        type: integer
      updated_at:
        type: string
    required:
    - created_at
    - guild_id
    - id
    - name
    - owner_id
    - updated_at
    type: object
  entity.Guild:
    properties:
      channels_quantity:
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        maxLength: 255
        minLength: 1
        type: string
      id:
        type: integer
      name:
        maxLength: 36
        minLength: 1
        type: string
      owner_id:
        type: integer
      updated_at:
        type: string
    required:
    - created_at
    - description
    - id
    - name
    - owner_id
    - updated_at
    type: object
  entity.UserProfile:
    properties:
      bio:
        maxLength: 32
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      display_name:
        maxLength: 16
        minLength: 4
        type: string
      guilds_quantity:
        type: integer
      id:
        type: integer
      messages_quantity:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - bio
    - created_at
    - display_name
    - id
    - updated_at
    - user_id
    type: object
host: localhost:3000
info:
  contact:
    email: gustavodiasa2121@gmail.com
    name: Gustavo Dias
    url: https://github.com/charmingruby
  description: This is a Discord like API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Telephony
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates an user
      parameters:
      - description: Credentials Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.CredentialsAuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.CredentialsAuthResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Authenticates an user
      tags:
      - Users
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates an user
      parameters:
      - description: Create User Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Creates an user
      tags:
      - Users
  /guilds:
    get:
      consumes:
      - application/json
      description: Fetch available guilds
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.FetchAvailableGuildsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Fetch available guilds
      tags:
      - Guilds
    post:
      consumes:
      - application/json
      description: Creates a guild
      parameters:
      - description: Create Guild Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.CreateGuildRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/endpoint.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoint.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Creates a guild
      tags:
      - Guilds
  /guilds/{guild_id}/channels:
    get:
      consumes:
      - application/json
      description: Fetch paginated channels of a guild
      parameters:
      - description: Fetch Guild Channels Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.FetchGuildChannelsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.FetchGuildChannelsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoint.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Fetch paginated channels of a guild
      tags:
      - Channels
    post:
      consumes:
      - application/json
      description: Creates a channel
      parameters:
      - description: Create Channel Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.CreateChannelRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/endpoint.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoint.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Creates a channel
      tags:
      - Channels
  /me:
    get:
      consumes:
      - application/json
      description: Gets authenticated user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.MeResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Gets authenticated user profile
      tags:
      - Profiles
  /me/profile:
    post:
      consumes:
      - application/json
      description: Creates an user profile
      parameters:
      - description: Create Profile Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.CreateProfileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoint.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Creates an user profile
      tags:
      - Profiles
  /welcome:
    get:
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Health Check
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    description: Ensures the user is authorized
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
