basePath: /api/v1
definitions:
  endpoint.CredentialsAuthData:
    properties:
      access_token:
        type: string
    type: object
  endpoint.CredentialsAuthRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  endpoint.CredentialsAuthResponse:
    properties:
      data:
        $ref: '#/definitions/endpoint.CredentialsAuthData'
      message:
        type: string
      status_code:
        type: integer
    type: object
  endpoint.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  endpoint.Response:
    properties:
      data: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:3000
info:
  contact:
    email: gustavodiasa2121@gmail.com
    name: Gustavo Dias
    url: https://github.com/charmingruby
  description: This is a Discord like API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Telephony
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates an user
      parameters:
      - description: Credentials Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.CredentialsAuthRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.CredentialsAuthResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Authenticates an user
      tags:
      - Users
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create User Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/endpoint.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/endpoint.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/endpoint.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoint.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Create user
      tags:
      - Users
  /welcome:
    get:
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.Response'
      summary: Welcome
      tags:
      - Health
swagger: "2.0"
